exports_files(
    [
        "llvm_blake3_no_asm_on_windows.patch",
        "llvm_smallvector_cstdint.patch",
        "llvm_zstd_no_asm_on_windows.patch",
    ],
    visibility = ["//visibility:public"],
)
