#include "code_browser/static_assets.h"

#include <cstddef>
#include <cstdio>
#include <fstream>
#include <sstream>

// Generated by the embed_file genrules in BUILD.bazel from web/.
extern "C" const unsigned char kWebIndexHtml[];
extern "C" const size_t kWebIndexHtmlSize;
extern "C" const unsigned char kWebAppJs[];
extern "C" const size_t kWebAppJsSize;
extern "C" const unsigned char kWebAppCss[];
extern "C" const size_t kWebAppCssSize;

namespace code_browser {

namespace {

auto Fnv1aEtag(std::string_view bytes) -> std::string {
  uint64_t h = 1469598103934665603ULL;
  for (const unsigned char c : bytes) {
    h ^= c;
    h *= 1099511628211ULL;
  }
  char buf[20];
  std::snprintf(buf, sizeof buf, "\"%016llx\"",
                static_cast<unsigned long long>(h));
  return buf;
}

struct Named {
  const char* file;
  const char* content_type;
};

auto Lookup(std::string_view request_path) -> std::optional<Named> {
  if (request_path == "/" || request_path == "/index.html")
    return Named{"index.html", "text/html; charset=utf-8"};
  if (request_path == "/app.js")
    return Named{"app.js", "text/javascript; charset=utf-8"};
  if (request_path == "/app.css")
    return Named{"app.css", "text/css; charset=utf-8"};
  return std::nullopt;
}

}  // namespace

auto StaticAssets::FromEmbedded() -> StaticAssets {
  StaticAssets a;
  const auto embed = [](const unsigned char* data, size_t size,
                        const char* content_type) {
    Embedded e;
    e.content_type = content_type;
    e.body = std::string_view(reinterpret_cast<const char*>(data), size);
    e.etag = Fnv1aEtag(e.body);
    return e;
  };
  a.index_html_ =
      embed(kWebIndexHtml, kWebIndexHtmlSize, "text/html; charset=utf-8");
  a.app_js_ = embed(kWebAppJs, kWebAppJsSize, "text/javascript; charset=utf-8");
  a.app_css_ = embed(kWebAppCss, kWebAppCssSize, "text/css; charset=utf-8");
  return a;
}

auto StaticAssets::FromDirectory(std::filesystem::path dir) -> StaticAssets {
  StaticAssets a;
  a.dir_ = std::move(dir);
  return a;
}

auto StaticAssets::Get(std::string_view request_path) const
    -> std::optional<StaticAsset> {
  const std::optional<Named> named = Lookup(request_path);
  if (!named) return std::nullopt;
  StaticAsset out;
  out.content_type = named->content_type;
  if (dir_) {
    std::ifstream in(*dir_ / named->file, std::ios::binary);
    if (!in) return std::nullopt;
    std::ostringstream ss;
    ss << in.rdbuf();
    out.body = ss.str();
    out.cache_control = "no-store";
    return out;
  }
  const Embedded& e = std::string_view(named->file) == "index.html"
                          ? index_html_
                      : std::string_view(named->file) == "app.js" ? app_js_
                                                                  : app_css_;
  out.body = std::string(e.body);
  out.etag = e.etag;
  out.cache_control = "max-age=0, must-revalidate";
  return out;
}

}  // namespace code_browser
