#!/usr/bin/env bash
# Integration test for the `<name>.browse` target generated by
# cpp_index_targets(): runs its launcher the way `bazel run` would (a
# BUILD_WORKSPACE_DIRECTORY holding a copy of the demo sources, RUNFILES_DIR
# set by the test runner exactly as `bazel run` sets it) and checks that the
# server it execs is serving that checkout over the index the build imported:
# the repo stats, a file's bytes, and a cross-target reference.
set -euo pipefail

launcher="$1"     # the generated index.browse.sh
get="$2"          # code_browser/http_get
shift 2
srcs=("$@")       # runfiles-relative demo sources

fail() { echo "FAIL: $*" >&2; exit 1; }

ws="$TEST_TMPDIR/ws"
for f in "${srcs[@]}"; do
  mkdir -p "$ws/$(dirname "$f")"
  cp -L "$f" "$ws/$f"
done

# 1. Without a workspace the launcher refuses rather than serving the sandbox.
if BUILD_WORKSPACE_DIRECTORY= "$launcher" --check >/dev/null 2>"$TEST_TMPDIR/nows.err"; then
  fail "launcher ran without BUILD_WORKSPACE_DIRECTORY"
fi
grep -q "bazel run" "$TEST_TMPDIR/nows.err" || { cat "$TEST_TMPDIR/nows.err" >&2; fail "unexpected error"; }

# 2. --check opens the database the build imported and prints its stats.
BUILD_WORKSPACE_DIRECTORY="$ws" "$launcher" --check 2>"$TEST_TMPDIR/check.err" \
  || { cat "$TEST_TMPDIR/check.err" >&2; fail "--check failed"; }
grep -q "4 files, 15 symbols" "$TEST_TMPDIR/check.err" \
  || { cat "$TEST_TMPDIR/check.err" >&2; fail "unexpected stats"; }

# 3. Serve the copy.  The launcher execs the server, so its pid is the server's.
BUILD_WORKSPACE_DIRECTORY="$ws" "$launcher" --port=0 --port-file="$TEST_TMPDIR/port" \
  --log-requests=false >"$TEST_TMPDIR/server.log" 2>&1 &
server=$!
trap 'kill "$server" 2>/dev/null || true' EXIT
for _ in $(seq 1 100); do [[ -s "$TEST_TMPDIR/port" ]] && break; sleep 0.1; done
[[ -s "$TEST_TMPDIR/port" ]] || { cat "$TEST_TMPDIR/server.log" >&2; fail "server did not start"; }
url="http://127.0.0.1:$(cat "$TEST_TMPDIR/port")"

"$get" "$url/api/repo" > "$TEST_TMPDIR/repo.json"
grep -q "\"root\": *\"$ws\"" "$TEST_TMPDIR/repo.json" \
  || { cat "$TEST_TMPDIR/repo.json" >&2; fail "root is not the workspace"; }
grep -q '"files": *4' "$TEST_TMPDIR/repo.json" || fail "repo stats"

"$get" "$url/api/file?path=bazel/testdata/demo.h" > "$TEST_TMPDIR/demo.h"
cmp "$TEST_TMPDIR/demo.h" "$ws/bazel/testdata/demo.h" || fail "file bytes differ"

"$get" "$url/api/symbol?usr=c:@S@Widget@FI@item_count_" > "$TEST_TMPDIR/sym.json"
id=$(grep -o '"id": *[0-9]*' "$TEST_TMPDIR/sym.json" | head -1 | grep -o '[0-9]*$')
[[ -n "$id" ]] || { cat "$TEST_TMPDIR/sym.json" >&2; fail "no symbol id"; }
"$get" "$url/api/refs/$id" > "$TEST_TMPDIR/refs.json"
grep -q '"line_text": *"  w.item_count_ = 4;"' "$TEST_TMPDIR/refs.json" \
  || { cat "$TEST_TMPDIR/refs.json" >&2; fail "cross-target reference"; }

# 4. Shutdown on SIGINT.
kill -INT "$server"
wait "$server" || fail "server exited non-zero on SIGINT"
trap - EXIT
echo "PASS"
