#!/usr/bin/env bash
# Integration test for the `<name>.compile_commands` target generated by
# cpp_format_targets(): runs its script the way `bazel run` would (a
# BUILD_WORKSPACE_DIRECTORY, a positional output path) and then has cpp_format
# itself consume the result as a compilation database -- which checks the JSON
# parses, that the entry is found under the `file` path the placeholder was
# filled with, and that the `directory` placeholder became the execution root:
# the copy of demo_main.cpp parsed here sits alone in a scratch workspace, so
# its `#include "demo.h"` resolves only through the entry's exec-root-relative
# `-isystem bazel/testdata`.
set -euo pipefail

gen="$1"          # the generated format.compile_commands.sh
cpp_format="$2"
config="$3"
src="$4"          # bazel/testdata/demo_main.cpp (runfiles-relative)

ws="$TEST_TMPDIR/ws"
mkdir -p "$ws/$(dirname "$src")"
cp "$src" "$ws/$src"
db="$TEST_TMPDIR/db"
mkdir -p "$db"

# 1. Generate.  The script derives the execution root from RUNFILES_DIR, which
#    the test runner sets exactly as `bazel run` does.
BUILD_WORKSPACE_DIRECTORY="$ws" "$gen" "$db/compile_commands.json"
json="$db/compile_commands.json"
[[ -s "$json" ]] || { echo "FAIL: no compile_commands.json written" >&2; exit 1; }

# 2. Shape: one entry per demo source, `file` under the workspace given, no
#    placeholder left behind, and the directory a real path.
n="$(grep -c '"directory"' "$json")"
[[ "$n" -eq 3 ]] || { echo "FAIL: expected 3 entries, got $n" >&2; cat "$json" >&2; exit 1; }
grep -q "\"file\":\"$ws/$src\"" "$json" || { echo "FAIL: no entry for $ws/$src" >&2; cat "$json" >&2; exit 1; }
if grep -q "__EXEC_ROOT__\|__WORKSPACE__" "$json"; then
  echo "FAIL: placeholder left in output" >&2; cat "$json" >&2; exit 1
fi
dir="$(sed -n 's/.*"directory":"\([^"]*\)".*/\1/p' "$json" | head -1)"
[[ -d "$dir" ]] || { echo "FAIL: directory $dir does not exist" >&2; exit 1; }

# 3. Without the database the lone copy cannot find demo.h ...
if "$cpp_format" --lint --config="$config" "$ws/$src" -- -std=c++17 >/dev/null 2>"$TEST_TMPDIR/nodb.err"; then
  echo "FAIL: parse without the database unexpectedly succeeded" >&2; exit 1
fi
grep -q "demo.h' file not found" "$TEST_TMPDIR/nodb.err" || {
  echo "FAIL: expected a missing-header error without the database" >&2
  cat "$TEST_TMPDIR/nodb.err" >&2; exit 1
}

# 4. ... and with it, the entry's directory and flags resolve every include
#    (the fixture conforms to the ruleset, so lint is clean: exit 0).
"$cpp_format" --lint --config="$config" -p "$db" "$ws/$src" >"$TEST_TMPDIR/db.out" 2>"$TEST_TMPDIR/db.err" || {
  echo "FAIL: parse with the database failed" >&2
  cat "$TEST_TMPDIR/db.out" "$TEST_TMPDIR/db.err" >&2; exit 1
}
if grep -q "file not found\|Could not auto-detect compilation database" "$TEST_TMPDIR/db.err"; then
  echo "FAIL: database not used" >&2; cat "$TEST_TMPDIR/db.err" >&2; exit 1
fi

echo "PASS"
