#!/usr/bin/env python3
"""Derive IWYU mappings for libc++'s private headers from its module map.

    tools/iwyu/gen_libcxx_mappings.py <libcxx>/include/module.modulemap.in \\
        > tools/iwyu/libcxx.imp

The C++ standard library the code is compiled against is the hermetic
toolchain's libc++, which is newer than the mappings IWYU ships: it splits every
public header into dozens of implementation headers (<__fwd/string.h>,
<__utility/move.h>, <__memory/unique_ptr.h>), and IWYU, finding a symbol there
and knowing no better, recommends including them.  libc++ says which public
header each one belongs to, in its module map:

    module string {
      module fwd { header "__fwd/string.h" }
      header "string"
    }

Every `header "__..."` inside a top-level module of `std` is private to that
module's own public header.  Re-run after a toolchain bump (the module map is
at external/llvm++llvm+llvm-project/libcxx/include/ in the output base).
"""

import re
import sys

TOKEN = re.compile(r'\bmodule\s+([\w.]+)[^{}\n]*\{|header\s+"([^"]+)"|\{|\}')


# Implementation headers several public headers share, which the module map
# therefore files under no public header at all.  IWYU takes whichever of the
# listed ones the file already includes.
SHARED = {
    "__tree": ["set", "map"],
    "__hash_table": ["unordered_map", "unordered_set"],
    "__node_handle": ["map", "set", "unordered_map", "unordered_set"],
    "__bit_reference": ["bitset", "vector"],
    "__split_buffer": ["deque", "vector"],
}


def mappings(text):
    # Blocks are the direct children of a top-level `std*` module: `std` holds
    # one per public header, `std_core` holds the ones (type_traits, ...) whose
    # parts other modules need without the whole header.
    depth = 0
    in_std = False
    blocks = []  # [name, [headers]]
    current = None
    for m in TOKEN.finditer(text):
        tok = m.group(0)
        if m.group(1) is not None:
            depth += 1
            if depth == 1:
                in_std = m.group(1).startswith("std")
            elif depth == 2 and in_std:
                current = [m.group(1), []]
                blocks.append(current)
        elif m.group(2) is not None:
            if current is not None and depth >= 2:
                current[1].append(m.group(2))
        elif tok == "{":
            depth += 1
        else:
            depth -= 1
            if depth < 2:
                current = None

    def is_public(h):
        return not h.startswith("__") and "/" not in h

    every_public = set(h for _, headers in blocks for h in headers if is_public(h))
    out = []
    for name, headers in blocks:
        public = [h for h in headers if is_public(h)]
        private = [h for h in headers if h.startswith("__")]
        if name in public or (not public and name in every_public):
            # A module names its own header after itself; std_core.type_traits
            # has no header of its own, std.type_traits does.
            targets = [name]
        elif public:
            targets = [public[0]]
        else:
            targets = []
        for h in private:
            for t in SHARED.get(h, targets):
                out.append((h, t))
    return sorted(set(out))


def main():
    rows = mappings(open(sys.argv[1]).read())
    print("# libc++'s private headers -> the public header each belongs to.")
    print("# Generated by tools/iwyu/gen_libcxx_mappings.py from libc++'s module map;")
    print("# do not edit.")
    print("[")
    for private, public in rows:
        print('  { include: ["<%s>", "private", "<%s>", "public"] },' % (private, public))
    print("]")


if __name__ == "__main__":
    main()
